config/routes.rb
Gc::Application.routes.draw do

  #вход на ресурс---------------------------------------------------------------
  root :to => 'arxivs#index'
  #маршруты авторизации---------------------------------------------------------
  devise_for :users  
  #маршруты архива решений------------------------------------------------------
  resources :imgs
  get "arxivs/getadr"
  get "arxivs/getper"  
  get "arxivs/getarx"  
  post "arxivs/index"
  
  get "arxivs/showall"
  match "arxivs/chengerada" => "arxivs#chengerada"
  match "arxivs/edit" => "arxivs#edit"
  match "arxivs/printarx" => "arxivs#printarx"
  resources :arxivs
  post "arxivs/sarxivs"
  match "arxivs/picture/:id" => "arxivs#picture"
  match "arxivs/archpgo/:id" => "arxivs#archpgo"
  match "arxivs/deleteimg/:id" => "arxivs#deleteimg"
  post "arxivs/chengerada"
  #Маршруты ПОГ-----------------------------------------------------------------
  resources :technics

  resources :animals

  resources :proplands

  resources :lands

  resources :prophouses

   post 'houses/wallsearch'
  get 'houses/wallsearch'   
  post 'houses/krovlsearch'
  get 'houses/krovlsearch'
  resources :houses
  
  post 'pers/familysearch'
  get 'pers/familysearch'
  post 'pers/surnamesearch'
  get 'pers/surnamesearch'
  post 'pers/namesearch'
  get 'pers/namesearch'
  post 'pers/midnamesearch'
  get 'pers/midnamesearch'
  resources :pers

  post 'roads/selcity'
  resources :roads

  post 'villages/selcouncil'
  resources :villages
  
    post 'allpgo/setpgo'
    get 'allpgo/setpgo'
    post 'allpgo/searchnum'
    get 'allpgo/searchnum'
    post 'allpgo/searchsur'
    get 'allpgo/searchsur'
   post 'allpgo/searchadre'
    get 'allpgo/searchadre'
    get "allpgo/index"
    get "allpgo/funcadmin"
     get "allpgo/nofound"
     get "allpgo/access_denied"


  post 'pgos/selbook'
  get "pgos/shows"
  resources :pgos

  resources :councils
  post 'books/selcouncil'
  get 'books/gobook'
  resources :books  
  

end

app/controllers/allpgo_controller.rb
# encoding: utf-8

class AllpgoController < ApplicationController
  before_filter :authenticate_user!
  
  def index
 
   if get_role < 0 then redirect_to :action => "access_denied" end
  end
  
  def funcadmin
     
  end 
  
    
  def searchadre

    q = params[:query].split(/с\. *|м\. *|село *|місто *|б\. *|буд\. *| , | ,*|, *| /)
    s = ''
    
    q.each { |qq| s = s + ' ' + qq.strip 
      s = s.strip}
    
 #   q = s.split(/  */)

#    @addre = Addre.joins("inner join (select roads.id, roads.city_id from roads
# inner join (select id from villages where (upper(villages.name_ukr) like upper('#{q[0]}%'))) as vl 
#on roads.city_id = vl.id where (upper(roads.value) like upper('#{q[1]}%'))) as
#vr on (addres.city_id = vr.city_id) and (addres.street_id = vr.id) and (addres.house like '#{q[2]}%')")
      
      @addre = Searchpgo.where("fulladdress ILIKE :input",{:input => "#{s}%"}).order('fulladdress')
    
 #     @addre.order()   
      pp = Array.new()
      i = 0
      @addre.each do |p|
#       if (@addre.rada_id == get_role) or (get_role == 0) then           
       if (p.rada_id == get_role) or (get_role == 0) then           
            pp[i] = Hash.new()
  #          @pgo = Pgo.where("address_id = #{p.id}").first
            pp[i].store("id",p.pgo_id)
            pp[i].store("num_1",p.numformat)
            pp[i].store("num_2",p.num_2)
  #          @per = Per.where("pgo_id = #{p.id}").first
  #          if @pers != nil then
  #              pp[i].store("surname",@pers.surname)
  #              pp[i].store("name",@pers.name)
  #              pp[i].store("midname",@pers.midname)
  #          else
   #             pp[i].store("surname","Мешканці")
  #              pp[i].store("name","не")
  #              pp[i].store("midname","визначені")        
  #          end
            pp[i].store("fullname",p.fullname)
            pp[i].store("fulladdres",p.descaddress)
            pp[i].store("adrquest",p.fulladdress)
            i = i + 1
       end
      end
    
    render :json => pp.to_json, :callback => params[:callback]
  end
     
  def searchsur
    
    q = params[:query].strip.split(/ , | ,*|, */, 3)
    s = ''
    
    q.each { |qq| s = s + ' ' + qq.strip 
      s = s.strip}
    
     
    
    
    @pers = Searchpgo.where("fullname ILIKE :input",{:input => "#{s}%"}).order('fullname')
  #  @pers = Per.where("upper(surname) LIKE upper(:input)",{:input => "#{q[0]}%"}).where("upper(name) LIKE upper(:input)",{:input => "#{q[1]}%"}).where("upper(midname) LIKE upper(:input)",{:input => "#{q[2]}%"}).order('surname','name', 'midname')

      pp = Array.new()
      i = 0
      @pers.each do |p|
 #      @pgo = Pgo.find(p.pgo_id)
 #      @addre = Addre.find(@pgo.address_id)
 #      if (@addre.rada_id == get_role) or (get_role == 0) then   
       if (p.rada_id == get_role) or (get_role == 0) then   
            pp[i] = Hash.new()

            pp[i].store("fullname",p.fullname)
  #          pp[i].store("name",p.name)
  #          pp[i].store("midname",p.midname)

            pp[i].store("id",p.pgo_id)
#            pp[i].store("num_1",@pgo.numformat)
#            pp[i].store("num_2",@pgo.num_2)
            pp[i].store("num_1",p.numformat)
            pp[i].store("num_2",p.num_2)
            pp[i].store("fulladdres",p.descaddress)

            i = i + 1

       end
      end

    render :json => pp.to_json, :callback => params[:callback]
  end
   
   
  def searchnum
    num = params[:query].split("-",2)
#    @pgo = Pgo.where("cast(num_1 as varchar(4)) LIKE :input",{:input => "#{num[0].to_i}%"}).where("cast(num_2 as varchar(4)) LIKE :input",{:input => "#{num[1]}%"}).order('num_1','num_2')
    @pgo =  Searchpgo.where("cast(num_1 as varchar(4)) LIKE :input",{:input => "#{num[0].to_i}%"}).where("cast(num_2 as varchar(4)) LIKE :input",{:input => "#{num[1]}%"}).order('num_1','num_2')
      
    
      pp = Array.new()
      i = 0
      @pgo.each do |p|
#            @addre = Addre.find(p.address_id)
            if (p.rada_id == get_role) or (get_role == 0) then   
            pp[i] = Hash.new()
#            @pers = Per.where("(pgo_id = #{p.id})").order('id').first
#            if @pers != nil then
#                pp[i].store("surname",@pers.surname)
#                pp[i].store("name",@pers.name)
#                pp[i].store("midname",@pers.midname)
#            else
#                pp[i].store("surname","Мешканці")
#                pp[i].store("name","не")
#                pp[i].store("midname","визначені")        
#            end
            pp[i].store("id",p.pgo_id)
            pp[i].store("fullname",p.fullname)  
            pp[i].store("num_1",p.numformat)
            pp[i].store("num_2",p.num_2)

            pp[i].store("fulladdres",p.descaddress)

            i = i + 1
       end
      end
    
    render :json => pp.to_json, :callback => params[:callback] 
    
  end
  
  def setpgo
   if  params['pgo-id'].to_i != -1 then 
    id_pgo = params['pgo-id'].to_i
    redirect_to pgo_path({:id => "#{id_pgo}"}) 
   else
      redirect_to :action => "nofound"
   end  
  end
  
  def nofound
    
  end
  
  def access_denied
    
  end
end

app/helpers/allpgo_helper.rb
module AllpgoHelper
end

app/views/allpgo/_goadmin.html.erb
<%= link_to 'До головних операцій', :action => "index", :controller => "allpgo" %>
<%= link_to 'До адміністративних елементів', :action => "funcadmin", :controller => "allpgo" %>

<hr align="center" width="100%" color="#C0C0C0" /> 

app/views/allpgo/_goback.html.erb
<%= link_to 'До головних операцій', :action => "index", :controller => "allpgo" %>
<hr align="center" width="100%" color="#C0C0C0" /> 

app/views/allpgo/_gocouncil.html.erb
<%= link_to 'До списку', :action => "index"%>
<%= link_to 'До головних операцій', :action => "index", :controller => "allpgo" %>
<%= link_to 'До адміністративних елементів', :action => "funcadmin", :controller => "allpgo" %>

 <hr align="center" width="100%" color="#C0C0C0" /> 

app/views/allpgo/_operation.html.erb
<%= link_to "Погосподарські книги", books_path %>
<%= link_to "Об'єкти погосподарського обліку", pgos_path %>

<%= link_to "Адміністративні елементи",  :action => "funcadmin", :controller => "allpgo"%>
<hr align="center" width="100%" color="#C0C0C0" /> 

app/views/allpgo/access_denied.html.erb
<%=  render :partial => 'goback'%>
<div align="center">
<div id="error_explanation" >
<h2 style="text-align: center">Доступ до системи обмежений</h2>

</div>
</div>  

app/views/allpgo/funcadmin.html.erb
<%=  render :partial => 'goback'%>
  <h2>
          <ol> Адміністративні елементи
  <hr align="center" width="100%" color="#C0C0C0" /> 
             <li>
            <%=  link_to_if  access_role, 'Робота з радами' ,councils_path %>
          
             </li><li>
            <%= link_to 'Робота з населеними пунктами', villages_path %>   
             </li><li>
            <%= link_to 'Робота з вулицями', roads_path %> 
             </li>
             <hr align="center" width="100%" color="#C0C0C0" /> 
         </ol> 
    
   </h2> 

app/views/allpgo/index.html.erb
<%= javascript_include_tag "jquery-ui-1.8.19.custom.min" %>
<%= javascript_include_tag "pgonum" %> 

<div>
  <%=  render :partial => 'operation' %>
</div>

<div id="findstatus">   

<%=  form_tag("/allpgo/setpgo", :method => "get") do -%>

<%= label_tag 'searchinput', "Пошук об'єкту обліку:" %> 

<%= text_field_tag("searchinput", nil, { :class => "ui-autocomplete-input", :size => 90}) %>  
<%= button_tag('Перейти') %> <br>
<%= radio_button_tag('surname','address',false,{})%> 
<label for="address">за адресою</label>  
<%= radio_button_tag('surname','surname',true,{})%>
<label for="surname">за власником</label> 
<%= radio_button_tag('surname','number',false,{})%>
<label for="number">за номером об'єкту обліку</label> 
<%= text_field_tag("pgo-id", -1, { :size => 1, :type => "hidden"}) %>  
<%-end%>
</div>

app/views/allpgo/nofound.html.erb
<%=  render :partial => 'goback'%>
<div align="center">
<div id="error_explanation" >
<h2 style="text-align: center">Жодний запис не містить вашого запросу. Інформацію по об'єкту не знайдено</h2>

</div>
</div>  