config/routes.rb
Gc::Application.routes.draw do

  #вход на ресурс---------------------------------------------------------------
  root :to => 'arxivs#index'
  #маршруты авторизации---------------------------------------------------------
  devise_for :users  
  #маршруты архива решений------------------------------------------------------
  resources :imgs
  get "arxivs/getadr"
  get "arxivs/getper"  
  get "arxivs/getarx"  
  post "arxivs/index"
  
  get "arxivs/showall"
  match "arxivs/chengerada" => "arxivs#chengerada"
  match "arxivs/edit" => "arxivs#edit"
  match "arxivs/printarx" => "arxivs#printarx"
  resources :arxivs
  post "arxivs/sarxivs"
  match "arxivs/picture/:id" => "arxivs#picture"
  match "arxivs/archpgo/:id" => "arxivs#archpgo"
  match "arxivs/deleteimg/:id" => "arxivs#deleteimg"
  post "arxivs/chengerada"
  #Маршруты ПОГ-----------------------------------------------------------------
  resources :technics

  resources :animals

  resources :proplands

  resources :lands

  resources :prophouses

   post 'houses/wallsearch'
  get 'houses/wallsearch'   
  post 'houses/krovlsearch'
  get 'houses/krovlsearch'
  resources :houses
  
  post 'pers/familysearch'
  get 'pers/familysearch'
  post 'pers/surnamesearch'
  get 'pers/surnamesearch'
  post 'pers/namesearch'
  get 'pers/namesearch'
  post 'pers/midnamesearch'
  get 'pers/midnamesearch'
  resources :pers

  post 'roads/selcity'
  resources :roads

  post 'villages/selcouncil'
  resources :villages
  
    post 'allpgo/setpgo'
    get 'allpgo/setpgo'
    post 'allpgo/searchnum'
    get 'allpgo/searchnum'
    post 'allpgo/searchsur'
    get 'allpgo/searchsur'
   post 'allpgo/searchadre'
    get 'allpgo/searchadre'
    get "allpgo/index"
    get "allpgo/funcadmin"
     get "allpgo/nofound"
     get "allpgo/access_denied"


  post 'pgos/selbook'
  get "pgos/shows"
  resources :pgos

  resources :councils
  post 'books/selcouncil'
  get 'books/gobook'
  resources :books  
  

end

app/models/technic.rb
class Technic < ActiveRecord::Base
set_table_name 'technics'
attr_accessible :datezap, :otvetstv, :comment
validates :datezap, :presence => true
belongs_to :pgo
has_many :proptechnics, :foreign_key => :technic_id
accepts_nested_attributes_for :proptechnics, :allow_destroy => true
end

app/controllers/technics_controller.rb
# encoding: utf-8

class TechnicsController < ApplicationController
  before_filter :authenticate_user!
  # GET /technics
  # GET /technics.json
  def index
    id_pgo = params[:id]
    @pgo = Pgo.find(id_pgo)
    @technics = @pgo.technics.order('datezap DESC').paginate(:page => params[:page], :per_page => 3)    

  render :layout => false 
  end

  # GET /technics/1
  # GET /technics/1.json
  def show
     
    @technic = Technic.find(params[:id])
    @pgo = Pgo.find(@technic.pgo_id)
  end

  # GET /technics/new
  # GET /technics/new.json
  def new
    id_pgo = params[:id]
    @pgo = Pgo.find(id_pgo)

      if @pgo.technics.order('datezap DESC').first != nil then
          @temp = @pgo.technics.order('datezap DESC').first
          @technic = @pgo.technics.build(@temp.attributes)
          @proparray = Array.new
            Glossarytechnic.order('id').each do |f|
              t = @temp.proptechnics.find(:first, :conditions => ["glossary_technic_id = #{f.id}"])
              if t != nil then @proparray[f.id] = t.value else
                @proparray[f.id] = '' end
            end          
      else    
          @technic = @pgo.technics.build
          @technic.proptechnics.build
          @proptechnics = @technic.proptechnics
          @proparray = Array.new
            Glossarytechnic.order('id').each do |f|
                @proparray[f.id] = ''
            end

      end
  end

  # GET /technics/1/edit
  def edit
     
    @technic = Technic.find(params[:id])
    @pgo = Pgo.find(@technic.pgo_id)
    @proptechnics = @technic.proptechnics 

      @proparray = Array.new
      Glossarytechnic.order('id').each do |f|
         @proptechnic = @technic.proptechnics.find(:first, :conditions => ["glossary_technic_id = #{f.id}"])
         if @proptechnic == nil then
           @proparray[f.id] = ''
         else
           @proparray[f.id] = @proptechnic.value.to_s
         end
      end
  end

  # POST /technics
  # POST /technics.json
  def create
       @pgo = Pgo.find(params[:pgo])
       @technic =  @pgo.technics.build(params[:technic])
       @proptechnics = @technic.proptechnics
       @proparray = Array.new 
        Glossarytechnic.all.each do |f|
          @proparray[f.id] = params[f.id.to_s]  
        end  
        flag = true
    Glossarytechnic.all.each do |f|
       if @proparray[f.id] != '' then
        flag =  @proparray[f.id].kind_of? Integer
        flag =  @proparray[f.id].to_i > 0
        if not flag then
          pprop = {}
          pprop["glossary_technic_id"] = f.id
          pprop["value"] = @proparray[f.id]          
          prop = @proptechnics.build
          prop.update_attributes(pprop)
        end
       end
    end      
    
      if @technic.save then
        
       if flag then
         Glossarytechnic.all.each do |f|
          if @proparray[f.id] != '' then 
          pprop = {}
          pprop["glossary_technic_id"] = f.id
          pprop["value"] = @proparray[f.id]          

            prop = @proptechnics.build
            prop.update_attributes(pprop)  
          end
         end
      
        
        redirect_to pgo_path({:id =>  @pgo.id, :pan => 5}), notice: 'Обход успішно створено.'
      else
         pvalue = @technic.attributes
         @technic.destroy
         @technic = Technic.new(pvalue)          
                
         render action: "new" 
        
      end
     else
      render action: "new" 
     end  
   end

  # PUT /technics/1
  # PUT /technics/1.json
  def update
    
    @technic = Technic.find(params[:id])
    @pgo = Pgo.find(@technic.pgo_id)
    @proptechnics = @technic.proptechnics
    @proparray = Array.new
    Glossarytechnic.all.each do |f|
          @proparray[f.id] = params[f.id.to_s]  
    end   
    flag = true
    Glossarytechnic.all.each do |f|
       if @proparray[f.id] != '' then
        flag =  @proparray[f.id].kind_of? Integer
        flag =  @proparray[f.id].to_i > 0
        if not flag then
          pprop = {}
          pprop["glossary_technic_id"] = f.id
          pprop["value"] = @proparray[f.id]          
          prop = @proptechnics.build
          prop.update_attributes(pprop)
        end
       end
    end      
     if @technic.update_attributes(params[:technic]) then
      
  
       if flag then
         Glossarytechnic.all.each do |f|
          if @proparray[f.id] != '' then 
          pprop = {}
          pprop["glossary_technic_id"] = f.id
          pprop["value"] =  @proparray[f.id]          
          prop = @technic.proptechnics.find(:first, :conditions => ["glossary_technic_id = #{f.id}"])
          if prop != nil then prop.update_attributes(pprop) else
            prop = @proptechnics.build
            prop.update_attributes(pprop)  
          end
          else
           prop = @technic.proptechnics.find(:first, :conditions => ["glossary_technic_id = #{f.id}"])
           if prop != nil then prop.destroy end
            
          end
         end
         redirect_to pgo_path({:id =>  @pgo.id, :pan => 5}), notice: 'Техніка оновлена.' 
       else
         render action: "edit" 
       end  
     else
      render action: "edit" 
     end  

  end

  # DELETE /technics/1
  # DELETE /technics/1.json
  def destroy
    @technic = technic.find(params[:id])
     @pgo = Pgo.find(@technic.pgo_id)
    @technic.proptechnics.each do |f|
      f.destroy
    end
    @technic.destroy
    redirect_to  pgo_path({:id =>  @pgo.id, :pan => 5})
  end
end

app/helpers/technics_helper.rb
module TechnicsHelper
end

app/views/technics/_form.html.erb
<%= form_for(@technic) do |f| %>
  <% if @technic.errors.any? %>
    <div id="error_explanation">
       <% count = 0%>
      <%@proptechnics.each do |p|%>  
      <%if p.errors.any? then 
        @prop = p
        count = count + 1
      end %>  
      <%end%>  
      
       <h2>Помилок: <%=  count %>. Необхідно виправити наступне:</h2>   
      
      <ul>
      <% @prop.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


<table align="center">
 <tr>
  <td><p align="center"><i><b>Номер об'єкту обліку</b></i></td>
  <td><p align="center"><i><b>Дата обходу</b></i></td>
  <td><p align="center"><i><b>Відповідальна особа</b></i></td> 
  <td><p align="center"><i><b>Додаткові відомості</b></i></td>
 </tr>
 <tr>
  <td><p align="center"><%= "#{@pgo.numformat}-#{@pgo.num_2}"%></td>
  <td><p align="center"><%= f.date_select :datezap, :start_year => 1980 %></td>
  <td><p align="center"><%=  f.text_field :otvetstv, :size => 20 %></td>
  <td><p align="center"><%= f.text_area :comment,  :size => "70x2" %></td>
 </tr>
</table>
<br/>
  <table align="center">
    <% Glossarytechnic.order('id').each do |prop| %>
<tr>
       <td width="50%"><p align="center"><i><b><%= prop.name %></b></i></td>

 
       <td><p align="center"><%= text_field_tag(prop.id, @proparray[prop.id], {:size => 10})%></td>  
       
 
</tr>
    <% end %>


</table>


 <br/>
<%= number_field_tag("pgo", @pgo.id, {:type => "hidden"}) %>   
 
  <div class="actions" align="center">
    <%= f.submit 'Прийняти'%>
  </div>
<% end %>

app/views/technics/_goadmin.html.erb
<%= link_to "До об'єкту", pgo_path({:id =>  @pgo.id, :pan => 5}) %>
<%= link_to "До списку", pgos_path({:book => @pgo.book_id, :page => getnumpage(@pgo.id, @pgo.book_id, 5)})%>
<%= link_to "До книг", books_path({:council => Book.find(@pgo.book_id).rada_id, :page => getbookpage(@pgo.book_id, 5)}) %>
<%= link_to 'До головних операцій', :action => "index", :controller => "allpgo" %>
<%= link_to 'До адміністративних елементів', :action => "funcadmin", :controller => "allpgo" %>
<h2 align="right"> Номер об'єкту: <%= @pgo.fullnum %> </h2>


<hr align="center" width="100%" color="#C0C0C0" /> 

app/views/technics/edit.html.erb
<%=  render :partial => 'goadmin'%>

<h1>Редагувати обход</h1>
 <hr align="center" width="100%" color="#C0C0C0" /> 
<%= render 'form' %>


</br>
  <hr align="center" width="100%" color="#C0C0C0" /> 

app/views/technics/index.html.erb

 <%= link_to 'Додати обхід', new_technic_path(:id => @pgo.id) %>
 <hr align="center" width="100%" color="#C0C0C0" /> 
 <br/>  
 <%if @technics.count != 0 then%>
<div class="digg_pagination">
    <div clas="page_info">
      <%= page_entries_info @technics %>
    </div>
    <%= will_paginate @technics, :container => false %>
  </div>

 <% @technics.each do |technic| %>
<table>
  
<tr>

<td width="5%"><p align="center"><i><b>Номер об'єкту обліку</b></i></td>
<td width="5%"><p align="center"><i><b>Дата обходу</b></i></td>
    <% technic.proptechnics.order('glossary_technic_id').each do |prop| %>
       <td><p align="center"><i><b><%= Glossarytechnic.find(prop.glossary_technic_id).name %></b></i></td>



<% end %>
<td><p align="center"><i><b>Відповідальна особа</b></i></td>
<td><p align="center"><i><b>Додаткові відомості</b></i></td>
</tr>
<tr>
  

  
    <td><p align="center"><i><%= @pgo.fullnum%></i></td>
    
    <td><p align="center"><i><%= link_to technic.datezap, edit_technic_path(technic) %></i></td>
  <% technic.proptechnics.order('glossary_technic_id').each do |prop| %>
    <td><p align="center"><i><%= prop.value %></i></td>
  <% end %>
    <td><p align="center"><i><%= technic.otvetstv %></i></td>
    <td><p align="center"><i><%= technic.comment %></i></td>
 
    

</tr>

</table>
<br/>

<% end %> 
<%end%>
  

app/views/technics/new.html.erb
<%=  render :partial => 'goadmin'%>

<h1>Новий обхід</h1>
 <hr align="center" width="100%" color="#C0C0C0" /> 
<%= render 'form' %>


</br>
  <hr align="center" width="100%" color="#C0C0C0" /> 

app/views/technics/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Редагувати обход', edit_technic_path(@technic) %>
</br>
<%= link_to "Повернутися до об'єкту", pgo_path({:id =>  @pgo.id, :pan => 5}) %>