config/routes.rb
Gc::Application.routes.draw do

  #вход на ресурс---------------------------------------------------------------
  root :to => 'arxivs#index'
  #маршруты авторизации---------------------------------------------------------
  devise_for :users  
  #маршруты архива решений------------------------------------------------------
  resources :imgs
  get "arxivs/getadr"
  get "arxivs/getper"  
  get "arxivs/getarx"  
  post "arxivs/index"
  
  get "arxivs/showall"
  match "arxivs/chengerada" => "arxivs#chengerada"
  match "arxivs/edit" => "arxivs#edit"
  match "arxivs/printarx" => "arxivs#printarx"
  resources :arxivs
  post "arxivs/sarxivs"
  match "arxivs/picture/:id" => "arxivs#picture"
  match "arxivs/archpgo/:id" => "arxivs#archpgo"
  match "arxivs/deleteimg/:id" => "arxivs#deleteimg"
  post "arxivs/chengerada"
  #Маршруты ПОГ-----------------------------------------------------------------
  resources :technics

  resources :animals

  resources :proplands

  resources :lands

  resources :prophouses

   post 'houses/wallsearch'
  get 'houses/wallsearch'   
  post 'houses/krovlsearch'
  get 'houses/krovlsearch'
  resources :houses
  
  post 'pers/familysearch'
  get 'pers/familysearch'
  post 'pers/surnamesearch'
  get 'pers/surnamesearch'
  post 'pers/namesearch'
  get 'pers/namesearch'
  post 'pers/midnamesearch'
  get 'pers/midnamesearch'
  resources :pers

  post 'roads/selcity'
  resources :roads

  post 'villages/selcouncil'
  resources :villages
  
    post 'allpgo/setpgo'
    get 'allpgo/setpgo'
    post 'allpgo/searchnum'
    get 'allpgo/searchnum'
    post 'allpgo/searchsur'
    get 'allpgo/searchsur'
   post 'allpgo/searchadre'
    get 'allpgo/searchadre'
    get "allpgo/index"
    get "allpgo/funcadmin"
     get "allpgo/nofound"
     get "allpgo/access_denied"


  post 'pgos/selbook'
  get "pgos/shows"
  resources :pgos

  resources :councils
  post 'books/selcouncil'
  get 'books/gobook'
  resources :books  
  

end

app/models/pgo.rb
# encoding: utf-8

class Pgo < ActiveRecord::Base

set_table_name 'pgos'
attr_accessible  :num_1, :num_2, :comment, :otvetstv, :address_id, :datezap
validates :num_1, :num_2, :presence => true
validates :num_1, :numericality => true
validates :num_2, :numericality => {:only_integer => true, :greater_than_or_equal_to => 1, :less_than_or_equal_to => 5}

belongs_to :book
has_many :pers, :foreign_key => :pgo_id
has_many :houses, :foreign_key => :pgo_id
has_many :lands, :foreign_key => :pgo_id
has_many :animals, :foreign_key => :pgo_id
has_many :technics, :foreign_key => :pgo_id

  def numformat
    self.num_1.to_s.rjust(4,'0')
  end
  
  def fullnum
    "#{numformat}-#{self.num_2}" 
  end

def self.adres_to_pgo(adr_str)
  @adr = Addres.find_last_by_full_address(adr_str) 
  if @adr.blank?||adr_str.length == 0
    -1
  else
    @pgo = Pgo.find_last_by_address_id(@adr.id)
    if @pgo.blank?
      -1
    else
      @pgo.id
    end
  end
end

end

app/controllers/pgos_controller.rb
# encoding: utf-8

class PgosController < ApplicationController
  before_filter :authenticate_user!
  # GET /pgos
  # GET /pgos.json
  def index
    
    id_council = getcouncil(params[:council])
 

      id_book = params[:book] 
    if id_book ==  nil then 
       if Council.find(id_council).books.first != nil then
         id_book = Council.find(id_council).books.order('num').first.id
       else 
         id_book = nil 
       end
    end
    
    if id_book != nil then
       @book = Book.find(id_book)
       if (get_role == @book.rada_id) or (get_role == 0)  then 
         id_council = @book.rada_id
       else
            if Council.find(id_council).books.first != nil then
              id_book = Council.find(id_council).books.order('num').first.id
            else 
              id_book = nil 
            end         
       end
      
    end     
    
    if id_book != nil then

       @book = Book.find(id_book)
       @book_id = id_book
       @pgos = @book.pgos.order('num_1').paginate(:page => params[:page], :per_page => 5) 
    else   
        @pgos = nil
        @book = nil
        @book_id = nil
    end           
   @council =  Council.find(id_council)
      
  end
  

  

  # GET /pgos/1
  # GET /pgos/1.json
  def show

    @panel_id = 0
    if params[:pan] != nil then 
      @panel_id = params[:pan]    

    end    
    @pgo = Pgo.find(params[:id])
    
    @book = Book.find(@pgo.book_id)
    @council = Council.find(@book.rada_id)
    if not ((get_role == @council.id) or (get_role == 0)) then
      redirect_to :action => "access_denied", :controller => "allpgo"
    end

  end
  
  def shows
    @pgo = Pgo.find(params[:id])
    if @pgo.num_2 == 1 then
       @per = @pgo.pers.find(:first, :conditions => ["family ilike :input",{:input => "голова"}])
    else
      @per = @pgo.pers.order('id').first
    end  
    @book = Book.find(@pgo.book_id)
    @council = Council.find(@book.rada_id)   
    @addre =  Addre.find(@pgo.address_id) 
   render :layout => false 
  end

  # GET /pgos/new
  # GET /pgos/new.json
  def new
        
    @page = params[:page]
    @book = Book.find(params[:book])
    @council = Council.find(params[:council])   


    @pgo = @book.pgos.new
    @addre = Addre.new
    @pgo.address_id = @addre.id
    @addre.rada_id = @council.id
    

    id_city = @council.villages.order('id').first.id
    if Village.find(id_city).roads.first != nil then
      id_street =  Village.find(id_city).roads.first.id 
    else
      id_street = nil 
    end
        @addre.street_id = id_street
        @addre.city_id = id_city
  end

  # GET /pgos/1/edit
  def edit
    
    
    @pgo = Pgo.find(params[:id])
    @book = Book.find(@pgo.book_id)
    @council = Council.find(@book.rada_id)   
    @addre =  Addre.find(@pgo.address_id)     


  end

  # POST /pgos
  # POST /pgos.json
  def create
    if params[:commit] != nil then    
          @book = Book.find(params[:book])
          @council = Council.find(params[:council])   
          @page = params[:page]

          

            pvalue = {}

            pvalue[:rada_id] = params[:council]
            pvalue[:city_id] = params[:Village][:id]
            pvalue[:street_id] = params[:Road][:id]
            pvalue[:house] = params[:house]
            pvalue[:suf_house] = params[:suf_house]
      


               @addre = Addre.new(pvalue)
              @pgo = @book.pgos.new(params[:pgo])


        if @addre.save then
              @addre.full_address = @addre.addresfull
              @addre.save
              @pgo.address_id = @addre.id 
              
              
              if @pgo.save then

                redirect_to pgo_path({:id =>  @pgo.id, :pan => 0}), notice: 'Об\'єкт ПГО успішно створений'
              else
                unless @addre.new_record? then
                  pvalue = @addre.attributes
                  @addre.destroy
                  @addre = Addre.new(pvalue)
            
                end  
          
                 render action: "new"
              end
        else
                render action: "new"
        end
    else
      @page = params[:page]
      if not params[:Road].nil? then 
        id_street = params[:Road][:id].to_i     
      end  
      if not params[:Village].nil? then 

        id_city = params[:Village][:id].to_i 
        
        if id_street != nil then 
          
          if Village.find(id_city).roads.find(:first, :conditions => ["id = #{id_street}"]) == nil then
            if Village.find(id_city).roads.first != nil then
              id_street = Village.find(id_city).roads.first.id
            else
              id_street = nil
            end
          end  
        else
           if Village.find(id_city).roads.first != nil then
              id_street = Village.find(id_city).roads.first.id
           end
          
        end 
        
        
        
        
        
      end 
      
          @book = Book.find(params[:book])
          @council = Council.find(params[:council])   


           
   
   
            pvalue = {}
            pvalue[:rada_id] = params[:council]
            pvalue[:city_id] = params[:Village][:id]
            pvalue[:street_id] = params[:Road][:id]
            pvalue[:house] = params[:house]
            pvalue[:suf_house] = params[:suf_house]
      
            
            @addre = Addre.new(pvalue)
            params[:pgo][:addres_id] = @addre.id 
            @pgo = @book.pgos.new(params[:pgo])
            
    
      render action: "new"
 
      
   end 
  end

  # PUT /pgos/1
  # PUT /pgos/1.json
  def update
    if params[:commit] != nil then
            @pgo = Pgo.find(params[:id])
            pvalue = {}
            pvalue[:rada_id] = params[:council]
            pvalue[:city_id] = params[:Village][:id]
            pvalue[:street_id] = params[:Road][:id]
            pvalue[:house] = params[:house]
            pvalue[:suf_house] = params[:suf_house]


            @addre = Addre.find(@pgo.address_id)

         
            if @addre.update_attributes(pvalue) then
             
            pvalue[:full_address] = @addre.addresfull 
            @addre.update_attributes(pvalue)
            if @pgo.update_attributes(params[:pgo]) then
              redirect_to pgo_path({:id =>  @pgo.id, :pan => 0}), notice: 'Інформацію успішно оновлено'
            else
              @book = Book.find(@pgo.book_id)
              @council = Council.find(@book.rada_id)                
              render action: "edit"
            end
            else
              @pgo.update_attributes(params[:pgo])
              @book = Book.find(@pgo.book_id)
              @council = Council.find(@book.rada_id)   
                
              render action: "edit"
            end
         
    else
        @pgo = Pgo.find(params[:id])
        @addre = Addre.find(@pgo.address_id)
        pvalue = {}
        if not params[:Road].nil? then 
         id_street = params[:Road][:id].to_i 
         
        end  
        if not params[:Village].nil? then 

        id_city = params[:Village][:id].to_i 
        pvalue[:city_id] = id_city
        if id_street != nil then 
          if Village.find(id_city).roads.where("id = #{id_street}").first == nil then
            if Village.find(id_city).roads.first != nil then
              id_street = Village.find(id_city).roads.first.id
            else
              id_street = nil
            end
          end 
          
        else
           if Village.find(id_city).roads.first != nil then
              id_street = Village.find(id_city).roads.first.id
           end
          
        end 
          pvalue[:street_id] = id_street
        
        end  
            
            
            pvalue[:rada_id] = params[:council]
            
            
            pvalue[:house] = params[:house]
            pvalue[:suf_house] = params[:suf_house]
           

         
            @addre.attributes = pvalue
            @pgo.attributes = params[:pgo]
            
              @book = Book.find(@pgo.book_id)
              @council = Council.find(@book.rada_id)        
            render action: "edit"
     

    end
  end

  # DELETE /pgos/1
  # DELETE /pgos/1.json
  def destroy
    @pgo = Pgo.find(params[:id])
    id_book = @pgo.book_id
    id_council = Book.find(id_book).rada_id
    @pgo.destroy
    redirect_to :action => "index", :council => id_council, :book => id_book
  end
  
  def selbook

    if not params[:Council].nil? then 
      id_council = params[:Council][:id].to_i 
      if Council.find(id_council).books.first != nil then
      id_book = Council.find(id_council).books.order('num').first.id
      else 
        id_book = nil
      end
    end
    if not params[:Book].nil? then 
      id_book = params[:Book][:id].to_i 
      id_council = params[:council].to_i 
    end

    redirect_to :action => "index", :council => id_council, :book => id_book   
  end
  


end

app/helpers/pgos_helper.rb
module PgosHelper
end

app/views/pgos/_form.html.erb

<%= form_for(@pgo) do |f| %>
  <% if @pgo.errors.any? %>
    <div id="error_explanation">
     <h2>Помилок: <%=@pgo.errors.count %>. Необхідно виправити наступне:</h2>   


      <ul>
      <% @pgo.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>



  <% if @addre.errors.any? %>
    <div id="error_explanation">
     <h2>Помилок: <%=@addre.errors.count %>. Необхідно виправити наступне:</h2>   


      <ul>
      <% @addre.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>




  <table border="1">
<tr>
<td width="10%"><p align="center"><i><b>Номер об'єкту</b></i></td>
<td width="10%"><p align="center"><i><b>Тип об'єкту</b></i></td>
<td width="20%"><p align="center"><i><b>Дата обходу</b></i></td>
<td width="10%"><p align="center"><i><b>Відповідальна особа</b></i></td>
<td width="20%"><p align="center"><i><b>Адреса</b></i></td>
<td width="20%"><p align="center"><i><b>Додаткова інформація</b></i></td>
</tr>
 <div class="field">
<tr>
 
  
    <td><p align="center"><i><b><%= f.number_field :num_1 , :size => 3 %></b></i></td>
    <td><p align="center"><i><b><%= f.number_field :num_2 , :size => 3 %></b></i></td>
    <td><p align="center"><i><b><%= f.date_select :datezap , :start_year => 1980 %></b></i></td>
    <td><p align="center"><i><b><%= f.text_field :otvetstv %></b></i></td> 
    <td><p align="center"><i><b>
            
            
<b>Населений пункт</b><br/>
<%= collection_select(:Village, :id, Council.find(@council.id).villages.order('id'), :id, :name_ukr, {:selected => @addre.city_id},{:onchange => 'submit("addres")'})%> <br/>
<b>Вулиця</b><br/>
<%= collection_select(:Road, :id, Village.find(@addre.city_id).roads.order('id'), :id, :fullroad, {:selected => @addre.street_id},{:onchange => 'submit("addres")'})%><br/>
<b>№ дому&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbspСуфікс</b><br/>
<%= text_field_tag('house', @addre.house, {:size => 2}) %>        
<%= text_field_tag('suf_house', @addre.suf_house, {:size => 2}) %>        
<%= number_field_tag("book", @book.id, {:type => "hidden"}) %>
<%= number_field_tag("page", @page, {:type => "hidden"}) %>
<%= number_field_tag("council", @council.id, {:type => "hidden"}) %>          
    </b></i></td>
     
   

     <td><p align="center"><i><b><%= f.text_area :comment, :size => "50x5" %></b></i></td>
</tr>



  </div>

  </table>
  </br> 

  <div class="actions" align="center">
    <%= f.submit 'Прийняти' %>
  </div>

<% end %>
 





app/views/pgos/edit.html.erb
<%= link_to "До об'єкту", pgo_path({:id =>  @pgo.id, :pan => 0}) %>
<%= link_to 'До списку', pgos_path({:book => @book.id, :page => getnumpage(@pgo.id, @book.id, 5)}) %>
<%=  render :partial => 'allpgo/goadmin'%>
<h1>Редагувати об'єкт погосподарського обліку</h1>
 <hr align="center" width="100%" color="#C0C0C0" />
<p>
  <b>Рада:</b>
  <%=  @council.name.to_s %>
</p>
<p>
  <b>Книга:</b>
  <%=  @book.numformat %>
</p>

<%= render 'form' %>


 <hr align="center" width="100%" color="#C0C0C0" />

app/views/pgos/index.html.erb
<%= link_to_if (@book != nil), "Додати", new_pgo_path({:book => @book.id, :council => @council.id, :page => params[:page]}) %>
<%= link_to_if (@book != nil), "До книг", books_path({:council => @council.id, :page => getbookpage(@book.id, 5)}) %>
<%=  render :partial => 'allpgo/goadmin'%>


<h1>Список об'єктів погосподарського обліку</h1>
 <hr align="center" width="100%" color="#C0C0C0" /> 

  <%if access_role then %>  
<%=form_for :Council, :url => {:action => :selbook} do |f|%>
<b> Рада:</b> 
<%= f.collection_select(:id, Council.order('id'), :id, :name, {:selected => @council.id},{:onchange => 'submit()'}) %>
<%end%>


<%else%>


<b> Рада:</b> <%=  @council.name %> 

<%end%>
<br/>
<%=form_for :Book, :url => {:action => :selbook} do |f|%>
<b> Оберіть книгу:</b>
<%=  f.collection_select(:id, @council.books.order('num'), :id, :numformat, { :selected => @book_id},{:onchange => 'submit()'}) %>
<%= number_field_tag("council", @council.id, {:type => "hidden"}) %>
<%end%>
<br/>

<%  if @book != nil then %>

  <table>
<tr>
<td style="border: solid black 1px" width="10%"><p align="center"><i><b>Номер об'єкту</b></i></td>
<td style="border: solid black 1px" width="10%"><p align="center"><i><b>Тип об'єкту</b></i></td>
<td style="border: solid black 1px" width="20%"><p align="center"><i><b>Дата обходу</b></i></td>
<td style="border: solid black 1px" width="10%"><p align="center"><i><b>Відповідальна особа</b></i></td>
<td style="border: solid black 1px" width="20%"><p align="center"><i><b>Адреса</b></i></td>
<td style="border: solid black 1px" width="20%"><p align="center"><i><b>Додаткова інформація</b></i></td>
</tr>


<div class="digg_pagination">
    <div clas="page_info">
      <%= page_entries_info @pgos %>
    </div>
    <%= will_paginate @pgos, :container => false %>
  </div>

<% @pgos.each do |pgo| %>
  <tr>

    
    <td style="border: solid black 1px"><p align="center"><%= link_to pgo.num_1.to_s.rjust(4,'0') , pgo_path({:id => pgo.id, :pan => 0}) %> </td>
    <td style="border: solid black 1px"><p align="center"><%= link_to pgo.num_2 , pgo_path({:id => pgo.id, :pan => 0}) %></td>
    <td style="border: solid black 1px"><p align="center"><%= pgo.datezap %></td>
    <td style="border: solid black 1px"><p align="center"><%= pgo.otvetstv  %></td>
     <td style="border: solid black 1px"><p align="center"> <%=  link_to Addre.find(pgo.address_id).addresfull , pgo_path({:id => pgo.id, :pan => 0}) %></td>
     <td style="border: solid black 1px"><p align="center"><%=  pgo.comment %></td>
     

  </tr>
<% end %>

</table>
<%else%>
<h1><p align="center">Не має книг</h1>

<%end%>



 <hr align="center" width="100%" color="#C0C0C0" /> 

app/views/pgos/new.html.erb
<%= link_to 'До списку', pgos_path({:book => @book.id, :page => @page}) %>
<%=  render :partial => 'allpgo/goadmin'%>
<h1>Новий об'єкт погосподарського обліку</h1>
 <hr align="center" width="100%" color="#C0C0C0" /> 
<p>
  <b>Рада:</b>
  <%=  @council.name.to_s %>
</p>
<p>
  <b>Книга:</b>
  <%=  @book.numformat %>
</p>
<%= render 'form' %>
</br>
 <hr align="center" width="100%" color="#C0C0C0" /> 

app/views/pgos/show.html.erb
<%= javascript_include_tag "jquery.tools.min" %>
<%= stylesheet_link_tag   "tabs.css" %>

<%= link_to "До списку", pgos_path({:book => @book.id, :page => getnumpage(@pgo.id, @book.id, 5)})%>
<%= link_to_if (@book != nil), "До книг", books_path({:council => @council.id, :page => getbookpage(@book.id, 5)}) %>
<%= link_to 'До головних операцій', :action => "index", :controller => "allpgo" %>
<%= link_to 'До адміністративних елементів', :action => "funcadmin", :controller => "allpgo" %>

<b align="right">  Номер об'єкту <%= @pgo.fullnum %> </b>
<hr align="center" width="100%" color="#C0C0C0" /> 

 <p id="notice"><%#= notice %></p>
<ul class="css-tabs">
  <li><a href=  <%=  "/pgos/shows?id=#{@pgo.id}" %> > Адреса об'єкту</a></li>
  <li><a href=  <%=  pers_path({:id => @pgo.id}) %> > Члени домогосподарства</a></li>
  <li><a href=  <%=  lands_path({:id => @pgo.id}) %> > Земельна ділянка</a></li>
  <% if (@pgo.num_2 != 4) then %>
     <li><a href=  <%= houses_path({:id => @pgo.id}) %> > Житловий будинок</a></li>
  <%end%>
  <% if (@pgo.num_2 != 5) then %>
     <li><a href=  <%=  animals_path({:id => @pgo.id}) %> > Худоба та птиця</a></li>
  <%end%>
  <% if (@pgo.num_2 == 1) then %>
      <li><a href= <%=  technics_path({:id => @pgo.id}) %> > Сільськогосподарська техніка</a></li>
  <%end%>
</ul>

<div class="css-panes">
  <div style="display:block"></div>
</div>

 <%= number_field_tag("panel-id", @panel_id, { :type => "hidden"}) %>  
 <%= javascript_include_tag "panel" %>

 <script type = "text/javascript">
    $(function() {
        n = $ ("#panel-id").val()
        num =  parseInt(n)
        $("ul.css-tabs").data("tabs").click(num)})
 </script>
 <br/>
<hr align="center" width="100%" color="#C0C0C0" /> 

app/views/pgos/shows.html.erb
<p align ="right"> <%=  @council.name.to_s %> рада, книга № <%=  @book.numformat %> </p> 

 <hr align="center" width="100%" color="#C0C0C0" /> 

<br/>

  <table border="1">
<tr>
<td width="5%"><p align="center"><i><b>Номер об'єкту</b></i></td>
<td width="5%"><p align="center"><i><b>Тип об'єкту</b></i></td>
<td width="10%"><p align="center"><i><b>Дата обходу</b></i></td>
<td width="10%"><p align="center"><i><b>Голова / Власник</b></i></td>
<td width="10%"><p align="center"><i><b>Відповідальна особа</b></i></td>
<td width="20%"><p align="center"><i><b>Адреса</b></i></td>
<td width="40%"><p align="center"><i><b>Додаткова інформація</b></i></td>
</tr>

<tr>
 
  
    <td><p align="center"><i><%= link_to  @pgo.numformat, edit_pgo_path({:id => @pgo.id})  %></i></td>
    <td><p align="center"><i><%= link_to  @pgo.num_2, edit_pgo_path({:id => @pgo.id}) %></i></td>
    <td><p align="center"><i><%= @pgo.datezap %></i></td>
    <td><p align="center"><i><%= if @per != nil then @per.fullname end %></i></td> 
    <td><p align="center"><i><%=  @pgo.otvetstv %></i></td> 
    <td><p align="center"><i> <%= link_to  @addre.addresfull, edit_pgo_path({:id => @pgo.id})   %> </i></td>
    <td><p align="center"><i><b><%= @pgo.comment %></b></i></td>
</tr>



 

  </table>







