config/routes.rb
Gc::Application.routes.draw do

  #вход на ресурс---------------------------------------------------------------
  root :to => 'arxivs#index'
  #маршруты авторизации---------------------------------------------------------
  devise_for :users  
  #маршруты архива решений------------------------------------------------------
  resources :imgs
  get "arxivs/getadr"
  get "arxivs/getper"  
  get "arxivs/getarx"  
  post "arxivs/index"
  
  get "arxivs/showall"
  match "arxivs/chengerada" => "arxivs#chengerada"
  match "arxivs/edit" => "arxivs#edit"
  match "arxivs/printarx" => "arxivs#printarx"
  resources :arxivs
  post "arxivs/sarxivs"
  match "arxivs/picture/:id" => "arxivs#picture"
  match "arxivs/archpgo/:id" => "arxivs#archpgo"
  match "arxivs/deleteimg/:id" => "arxivs#deleteimg"
  post "arxivs/chengerada"
  #Маршруты ПОГ-----------------------------------------------------------------
  resources :technics

  resources :animals

  resources :proplands

  resources :lands

  resources :prophouses

   post 'houses/wallsearch'
  get 'houses/wallsearch'   
  post 'houses/krovlsearch'
  get 'houses/krovlsearch'
  resources :houses
  
  post 'pers/familysearch'
  get 'pers/familysearch'
  post 'pers/surnamesearch'
  get 'pers/surnamesearch'
  post 'pers/namesearch'
  get 'pers/namesearch'
  post 'pers/midnamesearch'
  get 'pers/midnamesearch'
  resources :pers

  post 'roads/selcity'
  resources :roads

  post 'villages/selcouncil'
  resources :villages
  
    post 'allpgo/setpgo'
    get 'allpgo/setpgo'
    post 'allpgo/searchnum'
    get 'allpgo/searchnum'
    post 'allpgo/searchsur'
    get 'allpgo/searchsur'
   post 'allpgo/searchadre'
    get 'allpgo/searchadre'
    get "allpgo/index"
    get "allpgo/funcadmin"
     get "allpgo/nofound"
     get "allpgo/access_denied"


  post 'pgos/selbook'
  get "pgos/shows"
  resources :pgos

  resources :councils
  post 'books/selcouncil'
  get 'books/gobook'
  resources :books  
  

end

app/models/animal.rb
class Animal < ActiveRecord::Base
set_table_name 'animals'
attr_accessible :datezap, :otvetstv, :comment
validates :datezap,  :presence => true
belongs_to :pgo
has_many :propanimals, :foreign_key => :animal_id
accepts_nested_attributes_for :propanimals, :allow_destroy => true
end

app/controllers/animals_controller.rb
# encoding: utf-8

class AnimalsController < ApplicationController
  before_filter :authenticate_user!
  # GET /animals
  # GET /animals.json
  def index
    
    id_pgo = params[:id]
    @pgo = Pgo.find(id_pgo)
    @animals = @pgo.animals.order('datezap DESC').paginate(:page => params[:page], :per_page => 3)
    render :layout => false     
  end

  # GET /animals/1
  # GET /animals/1.json
  def show
    
    @animal = Animal.find(params[:id])
    @pgo = Pgo.find(@animal.pgo_id)
  end

  # GET /animals/new
  # GET /animals/new.json
  def new
    id_pgo = params[:id]
    @pgo = Pgo.find(id_pgo)

      if @pgo.animals.order('datezap DESC').first != nil then
          @temp = @pgo.animals.order('datezap DESC').first
          @animal = @pgo.animals.build(@temp.attributes)
          @proparray = Array.new
            Glossaryanimal.order('id').each do |f|
              t = @temp.propanimals.find(:first, :conditions => ["glossary_animal_id = #{f.id}"])
              if t != nil then @proparray[f.id] = t.value else
                @proparray[f.id] = '' end
            end          
      else    
          @animal = @pgo.animals.build
          @animal.propanimals.build
          @propanimals = @animal.propanimals
          @proparray = Array.new
            Glossaryanimal.order('id').each do |f|
                @proparray[f.id] = ''
            end

      end
   end
  # GET /animals/1/edit
  def edit
      
    @animal = Animal.find(params[:id])
    @pgo = Pgo.find(@animal.pgo_id)    
    @propanimals = @animal.propanimals 

      @proparray = Array.new
      Glossaryanimal.order('id').each do |f|
         @propanimal = @animal.propanimals.find(:first, :conditions => ["glossary_animal_id = #{f.id}"])
         if @propanimal == nil then
           @proparray[f.id] = ''
         else
           @proparray[f.id] = @propanimal.value.to_s
         end
      end

  end

  # POST /animals
  # POST /animals.json
  def create
          @pgo = Pgo.find(params[:pgo])
          @animal = @pgo.animals.build(params[:animal])
          @propanimals = @animal.propanimals
          @proparray = Array.new
        Glossaryanimal.all.each do |f|
          @proparray[f.id] = params[f.id.to_s]  
        end  
        flag = true
    Glossaryanimal.all.each do |f|
       if @proparray[f.id] != '' then
        flag =  @proparray[f.id].kind_of? Integer
        flag =  @proparray[f.id].to_i > 0
        if not flag then
          pprop = {}
          pprop["glossary_animal_id"] = f.id
          pprop["value"] = @proparray[f.id]          
          prop = @propanimals.build
          prop.update_attributes(pprop)
        end
       end
    end      
    
      if @animal.save then
        
       if flag then
         Glossaryanimal.all.each do |f|
          if @proparray[f.id] != '' then 
          pprop = {}
          pprop["glossary_animal_id"] = f.id
          pprop["value"] = @proparray[f.id]          

            prop = @propanimals.build
            prop.update_attributes(pprop)  
          end
         end
      
        
        redirect_to pgo_path({:id =>  @pgo.id, :pan => 4}), notice: 'Обход успішно створено.'
      else
         pvalue = @animal.attributes
         @animal.destroy
         @animal = Animal.new(pvalue)          
        
         render action: "new" 
        
      end
     else
      render action: "new" 
     end  
  end

  # PUT /animals/1
  # PUT /animals/1.json
  def update
  
    @animal = Animal.find(params[:id])
    @pgo = Pgo.find(@animal.pgo_id)
    @propanimals = @animal.propanimals
    @proparray = Array.new
    Glossaryanimal.all.each do |f|
          @proparray[f.id] = params[f.id.to_s]  
    end   
    flag = true
    Glossaryanimal.all.each do |f|
       if @proparray[f.id] != '' then
        flag =  @proparray[f.id].kind_of? Integer
        flag =  @proparray[f.id].to_i > 0
        if not flag then
          pprop = {}
          pprop["glossary_animal_id"] = f.id
          pprop["value"] = @proparray[f.id]          
          prop = @propanimals.build
          prop.update_attributes(pprop)
        end
       end
    end      
     if @animal.update_attributes(params[:animal]) then
      
  
       if flag then
         Glossaryanimal.all.each do |f|
          if @proparray[f.id] != '' then 
          pprop = {}
          pprop["glossary_animal_id"] = f.id
          pprop["value"] = @proparray[f.id]          
          prop = @animal.propanimals.find(:first, :conditions => ["glossary_animal_id = #{f.id}"])
          if prop != nil then 
            prop.update_attributes(pprop) 
          else
            prop = @propanimals.build
            prop.update_attributes(pprop)  
          end
          else
           prop = @animal.propanimals.find(:first, :conditions => ["glossary_animal_id = #{f.id}"])
           if prop != nil then 
             prop.destroy 
           end
            
          end
         end
         redirect_to pgo_path({:id =>  @pgo.id, :pan => 4}), notice: 'Худоба та птиця оновлені.' 
       else
         render action: "edit" 
       end  
     else
      render action: "edit" 
     end  

  end

  # DELETE /animals/1
  # DELETE /animals/1.json
  def destroy
    @animal = Animal.find(params[:id])
    @pgo = Pgo.find(@animal.pgo_id)
    @animal.propanimals.each do |f|
      f.destroy
    end
    @animal.destroy

     redirect_to pgo_path({:id =>  @pgo.id, :pan => 4})
 
  end
end

app/helpers/animals_helper.rb
module AnimalsHelper
end

app/views/animals/_form.html.erb
<%= form_for(@animal) do |f| %>
  <% if @animal.errors.any? %>
    <div id="error_explanation">
      <% count = 0%>
      <%@propanimals.each do |p|%>  
      <%if p.errors.any? then 
        @prop = p
        count = count + 1
      end %>  
      <%end%>  



      <h2>Помилок: <%= count %>. Необхідно виправити наступне:</h2>

      <ul>
        
      <% @prop.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

 
<table align ="center">
 <tr>
  <td><p align="center"><i><b>Номер об'єкту обліку</b></i></td>
  <td><p align="center"><i><b>Дата обходу</b></i></td>
  <td><p align="center"><i><b>Відповідальна особа</b></i></td> 
  <td><p align="center"><i><b>Додаткові відомості</b></i></td>
 </tr>
 <tr>
  <td><p align="center"><%= "#{@pgo.numformat}-#{@pgo.num_2}"%></td>
  <td><p align="center"><%= f.date_select :datezap , :start_year => 1980 %></td>
  <td><p align="center"><%=  f.text_field :otvetstv, :size => 20 %></td>
  <td><p align="center"><%= f.text_area :comment,  :size => "70x2" %></td>
 </tr>
</table>
<br/>
  <table align ="center">
    <% Glossaryanimal.order('id').each do |prop| %>
<tr>
       <td width="50%"><p align="center"><i><b><%= prop.name %></b></i></td>
       <td>
           <div class="field">
         <p align="center"><%= text_field_tag(prop.id, @proparray[prop.id], {:size => 10})%>
           </div> 
       </td>  
       
       
</tr>
    <% end %>


</table>

 <br/>
<%= number_field_tag("pgo", @pgo.id, {:type => "hidden"}) %>   
 
  <div class="actions" align="center">
    <%= f.submit 'Прийняти'%>
  </div>
<% end %>

app/views/animals/_goadmin.html.erb
<%= link_to "До об'єкту", pgo_path({:id =>  @pgo.id, :pan => 4}) %>
<%= link_to "До списку", pgos_path({:book => @pgo.book_id, :page => getnumpage(@pgo.id, @pgo.book_id, 5)})%>
<%= link_to "До книг", books_path({:council => Book.find(@pgo.book_id).rada_id, :page => getbookpage(@pgo.book_id, 5)}) %>
<%= link_to 'До головних операцій', :action => "index", :controller => "allpgo" %>
<%= link_to 'До адміністративних елементів', :action => "funcadmin", :controller => "allpgo" %>
<h2 align="right"> Номер об'єкту: <%= @pgo.fullnum %> </h2>


<hr align="center" width="100%" color="#C0C0C0" /> 

app/views/animals/edit.html.erb
<%=  render :partial => 'goadmin'%>

<h1>Редагувати обхід</h1>
 <hr align="center" width="100%" color="#C0C0C0" /> 
<%= render 'form' %>


</br>
  <hr align="center" width="100%" color="#C0C0C0" /> 

app/views/animals/index.html.erb

 <%= link_to 'Додати обхід', new_animal_path(:id => @pgo.id) %>
<hr align="center" width="100%" color="#C0C0C0" /> 
<br/>
<% if @animals.count != 0 then%>
<div class="digg_pagination">
    <div clas="page_info">
      <%= page_entries_info @animals %>
    </div>
    <%= will_paginate @animals, :container => false %>
  </div>
 <% @animals.each do |animal| %>
<table>
  
<tr>

<td width="5%"><p align="center"><i><b>Номер об'єкту обліку</b></i></td>
<td width="5%"><p align="center"><i><b>Дата обходу</b></i></td>
    <% animal.propanimals.order('glossary_animal_id').each do |prop| %>
       <td><p align="center"><i><b><%= Glossaryanimal.find(prop.glossary_animal_id).name %></b></i></td>



<% end %>
<td><p align="center"><i><b>Відповідальна особа</b></i></td>
<td><p align="center"><i><b>Додаткові відомості</b></i></td>
</tr>
<tr>
  
    <td><p align="center"><i><%=  @pgo.fullnum%></i></td>
  
    <td><p align="center"><i><%=  link_to animal.datezap, edit_animal_path(animal)  %></i></td>
  <% animal.propanimals.order('glossary_animal_id').each do |prop| %>
    <td><p align="center"><i><%= prop.value %></i></td>
  <% end %>
    <td><p align="center"><i><%= animal.otvetstv %></i></td>
    <td><p align="center"><i><%= animal.comment %></i></td>
  
     

</tr>

</table>
<br/>

<% end %>
<%end%>

app/views/animals/new.html.erb
<%=  render :partial => 'goadmin'%>

<h1>Новий обхід</h1>
 <hr align="center" width="100%" color="#C0C0C0" /> 
<%= render 'form' %>


</br>
  <hr align="center" width="100%" color="#C0C0C0" /> 

app/views/animals/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Редагувати обход', edit_animal_path(@animal) %>
</br>
<%= link_to "Повернутися до об'єкту", pgo_path({:id =>  @pgo.id, :pan => 4}) %>